datasource:
  host: "postgres-dev"
  db: "dev-db"
  user: "dev-user"
  password: "dev-password"

norris-api:
  base-url: "http://wiremock-dev:18081"
  connect-timeout-millis: 5000
  read-timeout-millis: 5000
