apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "postgres/postgres.yaml"
  - "wiremock/wiremock.yaml"
configMapGenerator:
  - name: "postgres-dev-data"
    files:
      - "postgres/sql/joke.data.sql"
  - name: "wiremock-dev-mappings"
    files:
#      - "wiremock/stub/norris-api-stub.json"
      - "wiremock/stub/norris-api-stub-with-errors.json"
