apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "skaffold-hands-on"
  labels:
    app.kubernetes.io/name: "skaffold-hands-on"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "skaffold-hands-on"
  labels:
    app.kubernetes.io/name: "skaffold-hands-on"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "skaffold-hands-on"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "skaffold-hands-on"
    spec:
      serviceAccountName: "skaffold-hands-on"
      containers:
        - name: "skaffold-hands-on"
          image: "ru.an1s9n/skaffold-hands-on"
          resources:
            requests:
              cpu: "500m"
              memory: "256M"
            limits:
              cpu: "1"
              memory: "512M"
          ports:
            - name: "http"
              containerPort: 8081
              protocol: "TCP"
          startupProbe:
            httpGet:
              path: "/actuator/health"
              port: 9091
              scheme: "HTTP"
            initialDelaySeconds: 1
            periodSeconds: 6
            failureThreshold: 100
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 9091
              scheme: "HTTP"
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 9091
              scheme: "HTTP"
            periodSeconds: 30
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: "app-config"
              mountPath: "/config"
              readOnly: true
            - name: "temp"
              mountPath: "/tmp"
      volumes:
        - name: "app-config"
          secret:
            secretName: "skaffold-hands-on-config"
            optional: true
        - name: "temp"
          emptyDir:
            sizeLimit: "10M"
