apiVersion: "v1"
kind: "Service"
metadata:
  name: "skaffold-hands-on"
  labels:
    app.kubernetes.io/name: "skaffold-hands-on"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "skaffold-hands-on"
  ports:
    - name: "http"
      port: 8081
      targetPort: "http"
